name: Assign me on Pull Request

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  assign-me:
    runs-on: ubuntu-latest
    steps:
      - name: Assign asterixorobelix to the PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/assignees \
            -d '{"assignees":["asterixorobelix"]}'