name: 🔧 CI/CD Issue
description: Report an issue with the CI/CD pipeline
title: "[CI/CD] "
labels: ["ci/cd"]

body:
  - type: dropdown
    id: workflow
    attributes:
      label: Affected Workflow
      description: Which workflow is having issues?
      options:
        - PR Validation
        - Release
        - Alpha Release
        - Dependency Updates
        - All workflows
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the CI/CD issue
      placeholder: "The release workflow is failing at the Android build step..."
    validations:
      required: true

  - type: input
    id: run_url
    attributes:
      label: Workflow Run URL
      description: Link to the failing workflow run (if applicable)
      placeholder: "https://github.com/owner/repo/actions/runs/123456789"

  - type: textarea
    id: error_logs
    attributes:
      label: Error Logs
      description: Paste relevant error logs or messages
      placeholder: "Error: Task :androidApp:bundleRelease FAILED"

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "The workflow should complete successfully and deploy to the app stores"